language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"
php:
- 5.6
- 7.2
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0
  global:
  - SVN_REPO: https://plugins.svn.wordpress.org/kuroneko-pay/
  - secure: "Kbe08TEkKMNKfrxpq6TViiHrnOdyCJzxgm2VbcQ6/50wueci+7HxpMeNZ2y6p9QyYiRv75dBaLUawSIdyDZrhg4RL3i262z+qfQ+FQALnPf86jpihzXIdnOhWqRraUBNpc8HsVghayWx60/wtn8XFu5zA/hndr2V4m335dz/iwtMCbDGrd9z7FZLQSPQQHEVJ9ybuu8WJ929/wjBVXT9JaUR7Z5poa2DOCa6WXu2jzfFIEYGjahq8eiWGQfxtTJnEU187hWHCZS6xtDpPwgSpUoVCZ9rQlnlu1Mio6n3nPHdPWWZnHNEho7MPb/iKO6s6jwls942UgmwcM3GQ4pRyKEptMoc/bcmQSx/9jeuyfWXXodEz7jzkSn26kmstENXJlhhWcNVQYO5S8fG37MiA2ANyWJ37AavGb/RGTe567xiNjAu5v4cHsgVMaune7jhzrD/aJG0ZEbU24wYkBWupRUJ1Zh2pGNrNKuYgKiWd8V42f6LeVt7fi1rsSrEGrWQvdNeQgQM+qOHDGyo0Ft5dIgH5UmvBYSyGLvWM5lKXI89CETwndfkpEKdjFvKWaymK8ZNb6QhTUgFXqDjJUqALHOrn+aJOcGRTjsMYTzWNcZyT8zfabZJoFc1ShYzB+3LOzBxzCjAq9MsRpz/E4SW4MkmqPvjQ6x/ygH+c97uaK8="
matrix:
  include:
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
services:
  - mysql
before_script:
- composer install
- curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
- source $HOME/.nvm/nvm.sh
- nvm install v6.11.0
- node --version
- npm install && npm run package
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
after_success: curl -L https://raw.githubusercontent.com/fumikito/travis2wpplugin/master/deploy.sh | bash
